from setuptools import setup, find_packages

setup(
    name='E-optimizer_adaptor',
    version='0.1.0',
    packages=find_packages(),
    install_requires=['torch'],
    author='Tong Zhao',
    author_email='tongzhao.zhaot@gmail.com',
    description='E opimizer adaptor',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/zhaotong94/E',
    #packages=find_packages(),
    py_modules=['E','ALTO'],
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Image Recognition",
        "Topic :: Scientific/Engineering :: Information Analysis",
        "Topic :: Scientific/Engineering :: Mathematics",
        "Topic :: Scientific/Engineering :: Physics",
        "Topic :: Scientific/Engineering :: Physics",
        "Topic :: Scientific/Engineering :: Visualization",
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
    ],
)